### ISSUE TITLE
The node-fetch Error

### ISSUE THREAD

**Issue by hkwin** [jkomyno/fetch-timeout#1]
I have already installed fetch-timeout and node-fetch at the same time, and then I import fetch-timeout to use it, and then  reported the following error:

Unable to resolve module `url` from `/Users/hkwin/Desktop/Code/git/Middle/guojiajia/node_modules/node-fetch/index.js`: Module does not exist in the module map or in these directories:
  /Users/hkwin/Desktop/Code/git/Middle/guojiajia/node_modules
,   /Users/hkwin/node_modules

how to fix ? thanks.

**Comment by jkomyno** [comment]
Can you please show me a snippet of this issue? Have you tried following along the example provided in the README? What version of NodeJS are you running?

**Comment by jkomyno** [comment]
Any update on this one? @hkwin

**Comment by hkwin** [comment]
@jkomyno I'm sorry I didn't reply, because I have taken other measures to solve the timeout problem of fetch at this time, so I forgot about it. I'm very sorry. I'll turn this issue off, and thank you very much for taking care of my problem.
